# .github/workflows/release.yml
name: Release
on:
    release:
        types: [published]
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: '3.13'
                  architecture: x64
            - run: python -m pip install --upgrade pip setuptools wheel
            - run: python -m pip install nox==2023.4.22
            - run: python -m pip install nox-poetry==1.0.3
            - run: python -m pip install poetry==1.5.1
            - run: nox -s tests-3.13
            - run: poetry build
            - run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
