# .github/workflows/release.yml
name: Release
on:
    release:
        types: [published]
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.4
            - uses: actions/setup-python@v2.2.1
              with:
                  python-version: '3.9'
                  architecture: x64
            - run: pip install nox==2023.4.22
            - run: pip install nox-poetry==1.0.3
            - run: pip install poetry==1.5. 
            - run: nox
            - run: poetry build
            - run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
